---
- name: Install patroni and postgresql to remote servers
  hosts: postgres_cluster
  gather_facts: no
  become: yes

  tasks:
    - name: Install postgresql
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - postgresql
        - postgresql-contrib

    - name: Stop and disable postgresql service
      service:
        name: postgresql
        enabled: no
        state: stopped

    - name: Create symlinks
      shell:
        cmd: "/usr/bin/ln -s /usr/lib/postgresql/12/bin/* /usr/sbin/"
      ignore_errors: yes

    - name: Install patroni
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - psycopg2
        - psycopg2-binary
        - patroni
        - python-etcd

    - name: Create folder for patroni config
      file:
        name: /etc/patroni
        state: directory

    - name: Create folder for patroni data
      file:
        name: /data/patroni
        state: directory
        recurse: yes
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Add patroni.service
      copy:
        src: ./services/patroni.service
        dest: /etc/systemd/system/patroni.service
        owner: root
        group: root
        mode: '0644'

    - name: Systemd daemon-reload
      systemd:
        daemon_reload: yes

    - name: Enabled patroni service
      service:
        name: patroni
        enabled: yes

- hosts: postgres1
  gather_facts: no
  become: yes

  tasks:
    - name: Add config patroni.yml to postgres1
      template:
        src: templates/patroni.yml.j2
        dest: /etc/patroni/config.yml
      vars:
        postgres_name: postgres1
        postgres_host: "{{ postgres1 }}"

    - name: Start patroni.service
      service:
        name: patroni
        state: started

- hosts: postgres2
  gather_facts: no
  become: yes

  tasks:
    - name: Add config patroni.yml to postgres2
      template:
        src: templates/patroni.yml.j2
        dest: /etc/patroni/config.yml
      vars:
        postgres_name: postgres2
        postgres_host: "{{ postgres2 }}"

    - name: Start patroni.service
      service:
        name: patroni
        state: started
