---
- name: Install etcd to remote servers
  hosts: etcd_cluster
  gather_facts: no
  become: yes

  tasks:
    - name: Install etcd
      apt:
        name: etcd
        state: latest

- hosts: etcd1
  gather_facts: no
  become: yes

  tasks:
    - name: Add config to etcd1
      template:
        src: templates/etcd.j2
        dest: /etc/default/etcd
      vars:
        etcd_name: etcd1
        etcd_host: "{{ etcd1 }}"

- hosts: etcd2
  gather_facts: no
  become: yes

  tasks:
    - name: Add config to etcd2
      template:
        src: templates/etcd.j2
        dest: /etc/default/etcd
      vars:
        etcd_name: etcd2
        etcd_host: "{{ etcd2 }}"

- hosts: etcd3
  gather_facts: no
  become: yes

  tasks:
    - name: Add config to etcd3
      template:
        src: templates/etcd.j2
        dest: /etc/default/etcd
      vars:
        etcd_name: etcd3
        etcd_host: "{{ etcd3 }}"

- hosts: etcd_cluster
  gather_facts: no
  become: yes

  tasks:
    - name: Restart etcd
      service:
        name: etcd
        state: restarted
