---
- name: Initial servers setup
  hosts: all
  become: yes

  tasks:
    - name: Create wheel group
      group:
        name: wheel
        state: present

    - name: Allow users in wheel group using sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: Create remote user with sudo privileges
      user:
        name: "{{ remote_user }}"
        state: present
        groups: wheel
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ remote_user }}"
        state: present
        key: "{{ item }}"
      with_file:
        - "{{ ssh_public_key_file }}"

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        cache_valid_time: "{{ cache_time }}"
        upgrade: yes

- hosts: etcd_cluster
  become: yes

  tasks:
    - name: Install etcd
      apt:
        name: etcd
        state: latest

- hosts: postgres_cluster
  become: yes

  tasks:
    - name: Install postgres
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-pip
        - python3-dev
        - gcc

    - name: Make sure psycopg2 is installed
      pip:
        name: psycopg2
        state: present

    - name: Change peer to md5
      replace:
        path: /etc/postgresql/12/main/pg_hba.conf
        regexp: "peer"
        replace: "md5"

    - name: Setup password for postgres user
      become_user: postgres
      community.postgresql.postgresql_user:
        user: postgres
        password: "{{ postgres_password }}"

    - name: restart postresql
      service:
        name: postgresql
        state: restarted

    - name: Disable postgresql service
      service:
        name: postgresql
        enabled: no

- hosts: all
  become: yes

  tasks:
    - name: Reboot servers
      reboot:
